version: '3.7'
services:
    web:
        build: ./
        ports:
            - "8080:80"
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
        volumes:
            - "./:/code"
            - "/eventStore"
