language: minimal

services:
  - docker

branches:
  only:
  - master

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
- docker build -t eventmodeling/dotnet:latest .
- docker push eventmodeling/dotnet:latest
