language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_cache:
	- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
	- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
	directories:
		- $HOME/.gradle/caches/
		- $HOME/.gradle/wrapper/

services:
  - docker

branches:
  only:
   - master

script:
 - docker build -t eventmodeling/dotnet:latest ./dotnetTeam
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
 - docker push eventmodeling/dotnet:latest
 - cd BookingPart && ./gradlew build jibDockerBuild
 - docker push eventmodeling/java:latest

