language: minimal

services:
  - docker

branches:
  only:
  - master

script:
- docker build -t eventmodeling/dotnet:latest .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push eventmodeling/dotnet:latest
