language: minimal

services:
  - docker

branches:
  only:
  - master

script:
- docker build -t eventmodeling/dotnet:latest .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" 
- docker push eventmodeling/dotnet:latest
