language: minimal

services:
  - docker

branches:
  only:
   - master

script:
 - docker build -t eventmodeling/dotnet:latest ./dotnetTeam
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
 - docker push eventmodeling/dotnet:latest

