version: '3.7'
services:
    proxy:
        image: traefik:latest
        restart: always
        ports:
          - "8080:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/traefik.toml
        networks:
          - web
    checkin:
        build: ./CheckIn
        volumes:
        - "eventStore:/home/events"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=checkin"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=Path:/checkin"
            - "traefik.port=5000"
        networks:
            - web
    php:
        build: ./BookingPhp
        volumes:
            - "eventStore:/events"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=php"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=Path:/room-inventory,/create_room,/change_type_price,/room-types"
            - "traefik.port=80"
        networks:
            - web
    dotnet:
        image: eventmodeling/dotnet:latest
        volumes:
            - "eventStore:/App/DATA"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=dotnet"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=PathPrefix:/Room/,/room/tobechecked,/room/checking,/room/checkingdone,/room/reportdamage,/room/checkoutguest"
            - "traefik.port=8080"
        networks:
            - web

networks:
    web:

volumes:
    eventStore:
        driver: local
