version: '3.7'
services:
    watchtower:
      image: v2tec/watchtower
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
         #       - /root/.docker/config.json:/config.json
      command: --interval 30 --label-enable

    proxy:
        image: traefik:latest
        restart: always
        ports:
          - "8080:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/traefik.toml
        networks:
          - web

    eventstore:
        image: eventstore/eventstore:latest
        ports:
            - "2113:2113"
        volumes:
          - "eventstore-data:/var/lib/eventstore"
        networks:
          - web

    booking-front:
        build: ./booking-front
        labels:
            - "traefik.enable=true"
            - "traefik.backend=booking-front"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=PathPrefixStrip:/booking"
            - "traefik.port=8080"
              #           - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - web

    checkin:
        build: ./CheckIn
        volumes:
        - "./eventStore:/home/events"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=checkin"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=Path:/checkin"
            - "traefik.port=5000"
              #          - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - web

    php:
        build: ./BookingPhp
        volumes:
            - "./eventStore:/events"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=php"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=Path:/room-inventory,/create_room,/change_type_price,/room-types"
            - "traefik.port=80"
              #            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - web

    dotnet:
        image: eventmodeling/dotnet:latest
        links:
            - eventstore
        volumes:
            - "./eventStore:/App/DATA"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=dotnet"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=PathPrefix:/Room/,/room/"
            - "traefik.port=8080"
            - "com.centurylinklabs.watchtower.enable=true"
        environment:
            - "WORKSHOP_EVENTSTORE_PASSWORD=${EVENTSTORE_PASSWORD}"
        networks:
            - web

    java:
        image: eventmodeling/java:latest
        volumes:
            - "./eventStore:/tmp/events"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=java"
            - "traefik.docker.network=web"
            - "traefik.frontend.rule=PathPrefix:/api/booking/book-room,/api/payment/details/"
            - "traefik.port=12378"
            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - web

volumes:
    eventstore-data:
        driver: local

networks:
    web:

